DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL,
    email TEXT NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT                         NOT NULL,
    description TEXT                         NOT NULL,
    available   bool                         NOT NULL,
    owner       BIGINT REFERENCES users (id) NOT NULL,
    request     BIGINT
);

DROP TABLE IF EXISTS bookings CASCADE;
CREATE TABLE IF NOT EXISTS bookings
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_ts TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    end_ts   TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    item     BIGINT REFERENCES items (id) NOT NULL,
    booker   BIGINT REFERENCES users (id),
    status   TEXT
);

DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text    TEXT                         NOT NULL,
    item    BIGINT REFERENCES items (id) NOT NULL,
    author  BIGINT REFERENCES users (id) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);