DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL,
    email TEXT NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT                         NOT NULL,
    description TEXT                         NOT NULL,
    available   bool                         NOT NULL,
    owner       BIGINT REFERENCES users (id) NOT NULL,
    request     BIGINT
);